<?php
$selectedSection = "artists";
?>


 <?php
 include("inc/artist-data.php");

if (isset($_GET["id"])) {
	$artist_id = $_GET["id"];
	if (isset($artist_data[$artist_id])) {
		$artist = $artist_data[$artist_id];
	}
}
if (!isset($artist)) {
	header("Location: artists.php");
	exit();
}
?>




<?php include('inc/header.php'); ?>

<span class="go-back">
	<a href="artists.php">Back to artists</a>
</span>

<section class="artist-profile">
	<div class="banner">
		<h1><?php echo $artist["name"];?></h1>
	</div>

	<div class="artist-image-container">
		<img src="<?php echo $artist["image"]; ?>">
	</div>

	<p><?php echo $artist["bio"]; ?></p>

	<div class="artist-videos">  <!-- videos generated by php using $artist-data array -->
	<?php 
		foreach($artist["video"] as $video){
			echo '<div class="video-container">';
					echo $video; 
			echo '</div>';
		}
	?>
	</div>


	<div class="artist-soundClouds">
	<?php 
		foreach($artist["soundCloud"] as $soundCloud){
			echo $soundCloud;
		}
	?>
	</div>
</section>

<?php include('inc/footer.php'); ?>