<?php
$selectedSection = "artists";
?>


 <?php
 include("inc/artist-data.php");

if (isset($_GET["id"])) {
	$artist_id = $_GET["id"];
	if (isset($artist_data[$artist_id])) {
		$artist = $artist_data[$artist_id];
	}
}
if (!isset($artist)) {
	header("Location: artists.php");
	exit();
}

$artistLinks = array();

if(isset($artist["links"]["soundCloud"])){
	$artistLinks[] = "<a href=" . $artist["links"]["soundCloud"] . "> <img class = 'big-soundcloud' src='img/soundcloud-icon-large.gif'></a>";
}

if(isset($artist["links"]["bandCamp"])){
	$artistLinks[] = "<a href=" . $artist["links"]["bandCamp"] . "> <img class = ' big-bandcamp' src='img/bandcamp-icon-large.gif'></a>";
}

if(isset($artist["links"]["spotify"])){
	$artistLinks[] = "<a href=" . $artist["links"]["spotify"] . "> <img class = 'big-spotify' src='img/spotify-icon-large.png'></a>";
}

?>



<?php include('inc/header.php'); ?>

<span class="go-back">
	<a href="artists.php">Back to artists</a>
</span>

<section class="artist-profile">
	<div class="banner">
		<h1><?php echo $artist["name"];?></h1>
	</div>

	<div class="artist-image-container">
		<img src="<?php echo $artist["image"]; ?>">
		<div class = "get-music">
		<?php foreach ($artistLinks as $artistLink){
			echo $artistLink;
		} ?>
	
		</div>
	</div>

	

	<p><?php echo $artist["bio"]; ?></p>

	<div class="artist-videos">  <!-- videos generated by php using $artist-data array -->
	<?php foreach($artist["video"] as $video){ ?>
			 <div class="video-container">
				<?php echo $video; ?>
			 </div>
	<?php } ?>

	</div>


	<div class="artist-soundClouds">

	<?php foreach($artist["soundCloud"] as $soundCloud){
			echo $soundCloud;
		  }
	?>
	</div>
</section>

<?php include('inc/footer.php'); ?>